### PR TITLE
Allow custom ServiceAccounts and explicitly set automountServiceAccountToken to true

### PR DESCRIPTION
**Pull request by doris-zhou**
This PR contains two changes.

1. Fix a bug where an existing ServiceAccount would be ignored if `serviceAccount.name` is specified, but `serviceAccount.create` is `false`. See https://github.com/prometheus-community/helm-charts/pull/755 for a similar change.
2. Add a value to explicitly set `automountServiceAccountToken`. It is considered best practice (see: CIS EKS Benchmark 4.1.6) to only mount the ServiceAccount token when necessary. Kubernetes currently implicitly sets this value to true, and it is usually necessary to mount the token when using RBAC, so prometheus-process-exporter should default to true.

### CODE REVIEW

**Review by silpamittapalli — APPROVED** [review]
LGTM

**Comment by doris-zhou** [comment]
@mumoshu Hello, would it be possible to get a review on this?

**Comment by mumoshu** [comment]
I'll review this probably tomorrow. Thanks for the PR!

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your contribution (and patience) @doris-zhou ☺️

**Pull request merged**
